name: Test Calculator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  test:
    runs-on: ubuntu-latest  # Replace with desired runner OS (e.g., macOS, Windows)

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"  # Replace with your Python version (adjust if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run tests
        run: |
          python -m unittest test.py  # Replace with your test execution command (e.g., pytest)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    # if: ${{ always() }}  # Uncomment this line if you want the deployment job to run regardless of test success

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          echo "Deploying the application..."  # Replace this with actual deployment commands
